### ISSUE TITLE
Rename file to JSX before passing it to the next loader

### ISSUE THREAD

**Issue by fregante** [frenzzy/svg-to-jsx-loader#2]
Thank you for this loader! It seems to work but some loaders won't recognize a JSX file with an SVG extension and end up not parsing it (example: https://github.com/microsoft/TypeScript/issues/10939)

Would it be possible for this loader to rename the file from `.svg` to `.jsx` so that loaders down the line automatically recognize it correctly?

**Comment by frenzzy** [comment]
You can apply as many loaders as you need per a specific file extension like this:
```js
// webpack.config.js
{
  module: {
    rules: [
      {
        test: /\.svg$/,
        use: [
          { loader: 'third-loader' }, // apply this loader after:
          { loader: 'seond-loader' }, // apply this loader after:
          { loader: 'svg-to-jsx-loader' }
        ]
      }
    ]
  }
}
```
Also I suggest to use [babel-plugin-inline-react-svg](https://github.com/airbnb/babel-plugin-inline-react-svg) or similar solution instead of webpack loaders.
(I am considering to deprecate this package in favor of Babel plugin)

**Comment by fregante** [comment]
Thank you for your reply!

Indeed I can inline them but TypeScript still refuses to do anything with it. 

I don’t have Babel in my pipeline and I’d rather keep it off since TypeScript does all of the work now. 

[In this case](https://github.com/sindresorhus/refined-github/pull/2610) I ended up using `buble-loader` to load the SVG straight into `React.createElement` calls (faster than Babel) and a micro loader to add `export default` in front of it, completely bypassing both TypeScript and this loader.
